### PR TITLE
Add custom error class and error hook

### PR DESCRIPTION
**Pull request by fwkoch**

### CODE REVIEW

**Comment by rowanc1** [comment]
Is it possible to catch all errors of a class validation at once? So that you can return a comprehensive list to a user?

```
x not defined and is required
y is out of bounds
z must be a string
```

Would this be useful for that?

**Comment by bsmithyman** [comment]
I like @rowanc1's idea. I am not 100% sure if it is possible given that some validation pieces are dependent on each other. Thoughts?

**Comment by fwkoch** [comment]
Really interesting. A few points - this could easily break with `@properties.validator` methods; these methods assume required properties are set and values are valid. You could get unwanted, non-validation errors by allowing these methods to run when things are in an invalid state.

However, ignoring these, we could make this work - I think, though, this would be an argument for moving the `raise ValidationError` to the `_error_hook`, rather than making those separate. If we keep things as they are (with validation errors outside of the hook), there isn't really a way to `continue` from the hook (without some funny business at least).

I'm not sure we want this builtin to the properties library, but maybe? Likely we should move the validation error into the error hook...

**Comment by rowanc1** [comment]
I think that even partial messages are helpful, so you only have to ask the class to validate twice instead of five times. So a list of `errors` could be helpful for other tools using this.

For example:
https://developer.github.com/v3/#client-errors



| title | description |
| ------------- |-------------|
| `missing` | This means a resource does not exist. |
| `missing_field` | This means a required field on a resource has not been set. |
| `invalid` | This means the formatting of a field is invalid. The documentation for that resource should be able to give you more specific information. |
| `already_exists` | This means another resource has the same value as this field. |

**Comment by bsmithyman** [comment]
This seems to work pretty well. I'd suggest we play with it in the existing projects that need this functionality, maybe merge in in a week or two?

**Pull request merged**
