### PR TITLE
Keep track of inheritance graph

### PR DESCRIPTION
**Pull request by bsmithyman**
The idea behind this piece of work is to preserve information about the explicit (vs. implicit) inheritance relationships between classes.

As the metaclass constructs HasProperties subclasses, it enters the baked-in inheritance structure into a dictionary that is stored on the class. This makes it possible to re-construct the data object inheritance path in its original form. This is useful for displaying the class structure (i.e., UML graphs), but also for replicating / reproducing the inheritance when writing translation libraries for data objects.

TODO:
- [ ] Possibly switch to using `collections.OrderedDict`, such that the creation order is preserved
- [ ] Possibly switch to a `list` instead of a `set`, to preserve precedence (`super`/`__mro__` order)

### CODE REVIEW

**Comment by bsmithyman** [comment]
image

**Comment by fwkoch** [comment]
Hi @bsmithyman, thanks for this. I see where you are going but I'm not totally convinced this is necessary to add to the metaclass. I think you can get _almost_ all the same functionality by just using the `__mro__`. Regarding your two purposes for this addition:

- Replicating/reproducing inheritance: With your method, you know the parent classes of `D` are `C` and `B`. The `__mro__` looks like `(D, C, A, B, properties.HasProperties, object)`. When reproducing this inheritance, you may construct `NewD` with the MRO as:

    ```python
    ...
    class NewD(NewC, NewA, NewB, NewBases):
        ...
    ```

    and I _think_ this will create an identical class to this (as you would get with `_CLS_GRAPH`):

    ```python
    ...
    class NewD(NewC, NewB):
        ...
    ```

- Displaying class structure: For this, it may be useful to have the actual parent list rather than the MRO so you don't get a bunch of extra lines on your UML graph. But that can be constructed outside the metaclass by doing something like:

    ```python
    _cls_dict = {
        k: tuple(
            c.__name__ for c in properties.HasProperties._REGISTRY[k].__mro__
            if issubclass(c, properties.HasProperties)
            and c.__name__ != k
        )
        for k in properties.HasProperties._REGISTRY
    }

    cls_graph = {
        k: set(
            c for c in _cls_dict[k]
            if c not in sum([_cls_dict[d] for d in _cls_dict[k]], ())
        )
        for k in _cls_dict
    }
    ```

    A bit ugly, but gives you this for your case above (identical to `_CLS_GRAPH`):

    image

    The only place where something is lost here is if you do:

    ```python
    class D(C, A, B):
        ...
    ```

    instead of:

    ```python
    class D(C, B):
        ...
    ```

    But I'd argue there's no reason be picky about this, since adding the parent classes (ie `A`) is redundant.

Can you follow up on this - is this last argument incorrect...? Is there another advantage to doing this in the metaclass that I'm totally overlooking?

**Comment by bsmithyman** [comment]
Hmm, interesting, thanks @fwkoch. I'll have a look and see if that deals with all of the use cases I'm thinking of.

**Comment by bsmithyman** [comment]
Not needed, per @fwkoch's code. Def. better to keep it out of the meta.

**Pull request closed without merging**
